### ISSUE TITLE
Not able to use it for video

### ISSUE THREAD

**Issue by dkhanna511** [trojerz/TOTB-reproducability#1]
Hi, thanks for the compilation of the Transparent Object Detection project with multiple trackers. I want to use it with ATOM tracker. I have realised that in the default code of ATOM, there is no mention of "totb" dataset. I want to run the tracker on a video of transparent objects and I dont really know how to proceed with it. 

A little help would be highly appreciated.

Thanks!

**Comment by trojerz** [comment]
Hi @dkhanna511,

You can check [here](https://github.com/trojerz/TOTB-reproducability/blob/main/Pytracking/pytracking/pytracking/run_tracker.txt), how to pass "totb" dataset to the tracker. Hope this helps.
